name: Begin Kosli Trail
description: ''

inputs:
  cli_version:
    description: "The version of the Kosli CLI to use"
    required: true

  flow_description:
    description: "The description of the Flow in which the Trail is beginning"
    required: true

runs:
  using: "composite"
  steps:
      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ inputs.cli_version }}

      - name: Create Kosli Flow
        shell: bash
        run:
          kosli create flow "${KOSLI_FLOW}"
            --description="${{ inputs.flow_description }}"

      - name: Begin Kosli Trail
        shell: bash
        run:
          kosli begin trail "${KOSLI_TRAIL}"
            --template-file=.kosli.yml

      - name: Write Trail URL to GitHub Step Summary
        shell: bash
        run: |
          url="https://app.kosli.com/${KOSLI_ORG}/flows/${KOSLI_FLOW}/trails/${KOSLI_TRAIL}"
          echo "[Kosli Trail](${url})" > "${GITHUB_STEP_SUMMARY}"
